name: Deploy

on:
  workflow_dispatch:
  push:
    branches:   # Filtrar somente para o branches especificados
      - main
      - develop

jobs:
  test-ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test
  deploy-test:
    needs: test-ci        # Dependência de test-ci, se executado
    if: github.ref == 'refs/heads/develop' # Só executar quando tiver feito um push para o develop
    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    environment: test    # Nome do ambiente
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker build -t setup-nodejs
      - run: echo "Deploy"
  deploy-production:
    needs: test-ci      # Dependência de test-ci, se executado
    if: github.ref == 'refs/heads/main' # Só executar quando tiver feito um push para o main
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker build -t setup-nodejs
      - run: echo "Deploy"